config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'pages#index'

  resources :artists, only: %i[show index]

  resources :mashups, only: %i[show index]
  put '/mashups/:id/sources', to: 'mashups#update_sources'

  resources :users, except: %i[new index]
  get 'signup', to: 'users#new', as: 'signup'

  resources :user_sessions, only: %i[create]
  get 'login', to: 'user_sessions#new', as: 'login'
  delete 'logout', to: 'user_sessions#destroy', as: 'logout'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :push_to_flash_alerts

  helper_method :not_authenticated, :require_admin

  before_action :require_login

  private

  # Allowed types: 'primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark'
  def push_to_flash_alerts(text = '', type: 'info')
    flash[:alerts] ||= []
    flash[:alerts] << { 'type' => type.to_s, 'text' => text.to_s }
  end

  # before_action
  def require_matching_user
    return if current_user == @user

    push_to_flash_alerts 'This action requires you to be logged in as another user.', type: 'danger'
    redirect_to main_app.root_path
  end

  # Used by Sorcery
  def not_authenticated
    redirect_to main_app.login_path, alert: 'Please login first'
  end

  # before_action. Used by RailsAdmin
  def require_admin
    return if current_user.admin?

    push_to_flash_alerts 'This action requires you to be logged in as another user.', type: 'danger'
    redirect_to main_app.root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def vk_posts_url(post_id)
    "https://vk.com/wall-39786657_#{post_id}"
  end

  def vk_profile_url(id)
    id.positive? ? "https://vk.com/id#{id}" : "https://vk.com/club#{id.abs}"
  end
end

app/views/application/nav/_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Mashup DB', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Artists', artists_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Mashups', mashups_path, class: 'nav-link' %>
      </li>
    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <% if logged_in? %>
        <% if current_user.admin? %>
          <li class="nav-item mx-2">
            <%= link_to 'Admin panel', rails_admin_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="navbar-text mx-2">
          Logged in as <%= link_to current_user.username, user_path(current_user) %>
        </li>
        <li class="nav-item mx-2">
          <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item mx-2">
          <%= link_to 'Login', login_path, class: 'nav-link' %>
        </li>
        <li class="nav-item mx-2">
          <%= link_to 'Signup', signup_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>