config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'pages#index'

  resources :artists, only: %i[show index]

  resources :mashups, only: %i[show index]
  put '/mashups/:id/sources', to: 'mashups#update_sources'

  resources :users, except: %i[new index]
  get 'signup', to: 'users#new', as: 'signup'

  resources :user_sessions, only: %i[create]
  get 'login', to: 'user_sessions#new', as: 'login'
  delete 'logout', to: 'user_sessions#destroy', as: 'logout'
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password,
            length: { minimum: 3 },
            if: -> { new_record? || changes[:crypted_password] }
  validates :password,
            confirmation: true,
            if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation,
            presence: true,
            if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
  validates :username, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  skip_before_action :require_login, only: %i[new create]
  before_action :require_matching_user, only: %i[show edit update destroy]

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_to @user, notice: 'User was successfully created'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'User was deleted'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: user, local: true do |f| %>
  <div class="form-group">
    <%= f.label :username, 'Username:' %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, 'Confirm password:' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Sign up', class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= render partial: 'users/form', locals: { user: @user } %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render partial: 'users/form', locals: { user: @user } %>

app/views/users/show.html.erb
<h1>Profile</h1>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Delete profile', user_path(@user), method: :delete, confirm: 'This will delete profile. Are you sure?' %>