config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root to: 'pages#index'

  resources :artists, only: %i[show index]

  resources :mashups, only: %i[show index]
  put '/mashups/:id/sources', to: 'mashups#update_sources'

  resources :users, except: %i[new index]
  get 'signup', to: 'users#new', as: 'signup'

  resources :user_sessions, only: %i[create]
  get 'login', to: 'user_sessions#new', as: 'login'
  delete 'logout', to: 'user_sessions#destroy', as: 'logout'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.alert = 'Login failed'
      render :new
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Logged out')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_with url: user_sessions_path, method: :post, local: true do |f| %>
  <div class="form-group">
    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'Password:' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'Login', class: 'btn btn-primary' %>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render partial: 'user_sessions/form' %>